name: release-preview
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  release-preview:
    uses: ./.github/workflows/release-common.yml
    with:
      dry_run: true
    secrets: inherit
