name: release-publish
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/release-base.yml
    with:
      dry_run: false
    secrets: inherit
